# Site
name: "Baker's Acre"
title: "Baker's Acre"
email: baker@thereverend.org
description: >-
  Making it work one day at time. Writing about recipes, products, and life lessons.

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-FWYTTQQ8ZK'
disqus: 'bakersacre'
pinterest: '59fb5c353969378f405aa2f2cf543f35'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
github_username: the-reverend

authors:
  rev:
    name: Rev
    display_name: Rev
    email: rev@thereverend.org
    web: https://www.thereverend.org
    twitter: https://twitter.com/th3reverend
    gravatar: e98628a49d97764f31893ad8b6bca6a7
    description: 'likes to pontificate on matters of life and death.'
  jon:
    name: Jon
    display_name: Jon
    avatar: 'assets/images/avatar.png'
    description: 'Lorem ipsum dolor.'
  baker:
    name: Baker
    display_name: Baker
    email: baker@thereverend.org
    gravatar: 96afea1d6e4e4237ba3ecf31723629f2
    description: 'likes to cook yummy stuff.'
  maker:
    name: Maker
    display_name: Maker
    gravatar: e98628a49d97764f31893ad8b6bca6a7
    email: maker@thereverend.org
    description: 'likes to build stuff by hand or with tools.'
  saver:
    name: Saver
    display_name: Saver
    email: saver@thereverend.org
    gravatar: abc7d1dab9f019b5952281924dd0649a
    description: 'likes to find frugality around every corner.'

prose:
  rooturl: '_posts'
  siteurl: 'http://www.bakersacre.com/'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - /_site
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'title'
        field:
          element: 'text'
          label: 'title'
          placeholder: 'Lorem Ipsum Dolor'
          alterable: true
      - name: 'description'
        field:
          element: 'text'
          label: 'description'
          placeholder: 'Lorem Ipsum Dolor'
          alterable: true
      - name: 'date'
        field:
          element: 'text'
          label: 'date'
          placeholder: 'YYYY-MM-DD HH:MM:SS -TZtz'
          value: 'CURRENT_DATETIME'
      - name: 'author'
        field:
          element: 'select'
          label: 'author'
          options:
            - name: baker
              value: baker
            - name: maker
              value: maker
            - name: saver
              value: saver
            - name: rev
              value: rev
      - name: 'image'
        field:
          element: 'text'
          label: 'image'
          placeholder: '/assets/images/loremipsum.jpg'
          alterable: true
      - name: 'categories'
        field:
          element: 'multiselect'
          label: 'categories'
          options:
            - name: budget
              value: budget
            - name: food
              value: food
            - name: home
              value: home
            - name: tech
              value: tech
      - name: 'featured'
        field:
          element: 'checkbox'
          label: 'featured?'
          value: false
      - name: 'hidden'
        field:
          element: 'checkbox'
          label: 'hidden?'
          value: false
      - name: 'comments'
        field:
          element: 'checkbox'
          label: 'comments?'
          value: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-8148538154279094"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
